# require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - .github/workflows/hexlet-check.yml

# BEGIN
Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
   Enabled: False

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/ArgumentsForwarding:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

# END